### PR TITLE
fixes #16 Add unit tests for sidebars collapse and focus mode

### LINKED ISSUE #16: Add unit tests for sidebars collapse and focus mode.
Create tickets for other tests, we can help and practice.

### PR DESCRIPTION
**Pull request by Rahul139-stack**
PLEASE REVIEW AND APPROVE IT

### CODE REVIEW

**Review by sanjayaapna — APPROVED** [review]

**Review by wildone — CHANGES_REQUESTED** [review]
do we want to have same names for files: SplitPane.showcase.vue and splitpane.spec.ts?

**Comment by Rahul139-stack** [comment]
> do we want to have same names for files: SplitPane.showcase.vue and splitpane.spec.ts?

It is not required with same files name

**Comment by wildone** [comment]
@Rahul139-stack did you mean to close this or merge it?

**Comment by Rahul139-stack** [comment]
> @Rahul139-stack did you mean to close this or merge it?

Requested to merge

**Comment by wildone** [comment]
lets rename splitpane.spec.ts to SplitPane.spec.ts as its related.

**Pull request merged**
