### PR TITLE
#35 added custom icon for app and #40 updated the product name

### PR DESCRIPTION
**Pull request by Rahul139-stack**
please review and Approve it

### CODE REVIEW

**Review by ankitvats1 — APPROVED** [review]

**Review by sanjayaapna — COMMENTED** [review]
if possible then change the PNG into a transparent image else look good to me.

**Review by wildone — CHANGES_REQUESTED** [review]
icns needs to be there for mac build?

**Comment by wildone** [comment]
need to fix conflict.

**Comment by wildone** [comment]
@Rahul139-stack need to fix the conflict.

**Review by wildone — APPROVED** [review]

**Review by Shivam-apna — APPROVED** [review]

**Review by ankitvats1 — APPROVED** [review]

**Review by sanjayaapna — APPROVED** [review]

**Comment by wildone** [comment]
@Rahul139-stack need to fix the conflicts.

**Review by rohitgupta274509 — APPROVED** [review]

**Comment by wildone** [comment]
@Rahul139-stack need to merge develop into this branch and fix the conflicts.

**Review by sanjayaapna — APPROVED** [review]

**Review by Shivam-apna — APPROVED** [review]

**Review by rohitgupta274509 — APPROVED** [review]

**Pull request merged**
